title: Esme Beauty Care
email: contacto@esmebeautycare.com
phone: 661-612-2841
address: Romualdo Gallardo Orozco 1317, Lucio Blanco, 22706 Playas de Rosarito, B.C. México
description: >- # this means to ignore newlines until "baseurl:"
  Atrévete a lucir un rostro hidratado y libre de impurezas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://esmebeautycare.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-02PLEPHJF3

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      lang: "es-mx"
      lazy: true
      image: 
        path: /img/logo/og-img.png
        height: 192
        width: 192
      author: Rosarito Centro  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
